config/routes.rb
Postit::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, :except => :destroy do
  	resources :comments
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :user
 belongs_to :post

 validates :comment_text, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :post_categories
	has_many :categories, through: :post_categories
	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :url, presence: true
	validates :description, presence: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.create(comment_text:params[:comment][:comment_text],user_id:1,post_id:params[:post_id])
  	if @comment.save
  		flash[:notice] = "Comment was successfully created."
  		redirect_to post_path(params[:post_id])
  	else #validation failure
  			flash[:notice] = "Comment can't be blank"
  			redirect_to post_path(params[:post_id])
  	end

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all
  end

  def new
    @post=Post.new
  end

  def create
  	@post = Post.create(params[:post])
  	@post.user_id = 1 #To Do - Put in real user

  	if @post.save
  		flash[:notice] = "Post was successfully created."
  		redirect_to '/'
  	else #validation failure
      render :new
  	end
  end

  def show 
  	@post = Post.find(params[:id])
    @comment = @post.comments
    @new_comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:notice] = "You successfully updated your post."
      redirect_to "/posts/#{@post.id}"
    else #validation failure
      render :edit
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'link', '' %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
	<% if @post.errors.any? %>
		<div class="alert alert-error">
			<%= @post.errors.full_messages.join(', ') %>
		</div>
	<% end %>


	<%= form_for @post do |f| %>

		<%= f.label :title %>
		<%= f.text_field :title %>
		<br/>
		<%= f.label :url %>
		<%= f.text_field :url %>
		<br/>
		<%= f.label :description %>
		<%= f.text_area :description, rows: "3" %>
		<br/>
		<%= f.submit class: "btn btn-primary" %>

	<% end %>

app/views/posts/_show.html.erb
<div class="span8">

<% if @posts %>
<h5>Welcome to the project template!</h5>
	
	<% @posts.each do |post| %>
		<div class="well">
			<p><%= link_to post.title, post.url %></p>
			<p><%= post.description %></p>
			<p>post by <%=post.user.username %></p>
			<br/>
		  <%= link_to "Edit", edit_post_path(post) %>
		  <br/>
		  <%= link_to "#{post.comments.count} Comments", post_path(post.id) %>
		</div>
	<% end %>

<% elsif @post %>

	<h3><%= link_to @post.title, @post.url %></h3>
	<p><%= @post.description %></p>

	<%= form_for @new_comment, url: post_comments_path(@post.id) do |f| %>
		<%= f.label :comment_text %>
		<%= f.text_area :comment_text, rows: "3" %>
		<br/>
		<%= f.submit class: "btn btn-primary" %>
	<% end %>


	<h5>Comments:</h5>

	<% @comment.each do |comment| %>
		<div class="well">
			<p><%= comment.comment_text %></p>
			<p>by <%= User.find(comment.user_id).username %></p>
		</div>
	<% end %>
<% end %>

</div>

app/views/posts/edit.html.erb
<div class="span8">
	<h3>Edit your post</h3>
	<%= render "form" %>
</div>

app/views/posts/index.html.erb
<%= render "show" %>

<!-- <div class="span8 well">
	<% @posts.each do |post| %>
		<p><%= link_to post.title, post.url %></p>
		<p><%= post.description %></p>
		<p>post by <%=post.user.username %></p>
		<br/>
	  <%= link_to "Edit", edit_post_path(post) %>
	<% end %>
</div> -->

app/views/posts/new.html.erb
<div class="span8">
<h3>Create a new post</h3>
	<%= render "form" %>
</div>





<!-- 
Old code. Create the form without rails form_for 
method.

<h3>Create a new post</h3>

<form action="/posts" method="post">
	<p>Titel</p>
	<input type="text", name="post[title]", class="input-large"/>
	<p>URL</p>
	<input type="text", name="post[url]", class="input-large"/>
	<p>Description</p>
	<textarea rows="3" name="post[description]", class="input-large"></textarea>
	</br>
	<input type="submit", value="Create Post", class="btn btn-primary">
</form>

 -->

app/views/posts/show.html.erb
<%= render "show" %>